/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import enigma.Enigma;
import javax.swing.JFrame;

/**
 *
 * @author facud
 */
public class RotorsChoice extends javax.swing.JFrame {
    private JFrame parent;
    private Enigma enigma;
    
    /**
     * Creates new form RotorsChoice
     */
    public RotorsChoice() {
        initComponents();
        setLocationRelativeTo(parent);
    }
    
    public RotorsChoice(JFrame parent, Enigma enigma){
        this.parent = parent;
        this.enigma = enigma;
        initComponents();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rotorsChoiceP1 = new GUI.RotorsChoicePanel(this, this.enigma);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rotores");
        setAlwaysOnTop(true);
        setName("Rotores"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(973, 448));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(rotorsChoiceP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.RotorsChoicePanel rotorsChoiceP1;
    // End of variables declaration//GEN-END:variables
}
